using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Collections;
using System.Data.Services.Client;

namespace Facebook.Api
{
    public class FacebookServiceQuery<TElement> : FacebookServiceQuery, IEnumerable<TElement>, IQueryable<TElement>
    {

        /// <summary>
        /// Creates a new FacebookServiceQuery<TElement> with the query option set in the URI generated by the returned query.
        /// </summary>
        /// <param name="name"></param>
        /// <param name="value"></param>
        /// <returns></returns>
        public FacebookServiceQuery<TElement> AddQueryOption(string name, object value)
        {
            throw new NotImplementedException();
        }

        public override System.Linq.Expressions.Expression Expression
        {
            get { throw new NotImplementedException(); }
        }

        public override IQueryProvider Provider
        {
            get { throw new NotImplementedException(); }
        }

        public override Type ElementType
        {
            get { throw new NotImplementedException(); }
        }

        public override Uri RequestUri
        {
            get { throw new NotImplementedException(); }
        }

        /// <summary>
        /// Represents the URI of the query to the data service.
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            return base.ToString();
        }

        public IEnumerator<TElement> GetEnumerator()
        {
            throw new NotImplementedException();
        }

    }
}
