




// --------------------------------
// <copyright file="GraphObjectBuilder.tt" company="Thuzi, LLC">
//     Copyright (c) 2010 Thuzi, LLC (thuzi.com)
// </copyright>
// <author>Nathan Totten (ntotten.com) and Jim Zimmerman (jimzimmerman.com)</author>
// <license>Released under the terms of the Microsoft Public License (Ms-PL)</license>
// <website>http://facebooksdk.codeplex.com</website>
// <autogenerated>
//   This file was generated using GraphObjectBuilder.tt.
//   Any changes made manually will be lost next time the file is regenerated.
// </autogenerated>
// ---------------------------------

 
 
 

using System;
using System.Collections.ObjectModel; 
using System.Data.Linq.Mapping;
using System.ComponentModel.DataAnnotations;


namespace Facebook.Api.Graph {

}

